speedcubingfrance/speedcubingfrance.org

- _posts/news/2018-01-30-wca-redbull.md
Premier essai avec Markdown, j'espère que tout est bon (notamment les ** et le *** pour séparer les 2 versions)
> Ajout news Redbull

- _posts/news/2018-03-05-wca-dues-system.md
> Ajout news WCA Dues System

- app/helpers/application_helper.rb
- app/views/shared/_compact_table.html.erb
- app/webpacker/afs/index.js
- package.json
- yarn.lock
> Tri possible pour tous les tableaux qui utilisent la vue compact_tables

- app/webpacker/packs/stylesheets.scss
Fixes #35.
Faut croire que la nouvelle version de bootstrap corrige le problème d'alignement que j'avais initialement corrigé à la main.
> Fix checkbox alignment

- app/helpers/application_helper.rb
- app/mailers/notification_mailer.rb
- app/models/competition.rb
- app/views/notification_mailer/notify_of_new_competition.html.erb
- app/views/notification_mailer/notify_of_new_competition.text.erb
- config/locales/fr.yml
- db/migrate/20190102234510_add_announced_at_to_competitions.rb
- db/schema.rb
- lib/tasks/scheduler.rake
> Envoi de notifications le lendemain de l'annonce d'une compétition française

- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
- config/locales/fr.yml
- db/migrate/20190311215115_add_city_to_users.rb
- db/schema.rb
> Add city to user profile

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/edit.html.erb
- config/locales/fr.yml
- db/migrate/20190326143535_add_discussion_subscription_to_users.rb
- db/migrate/20190402113930_add_newsletter_subscription_to_users.rb
- db/schema.rb
- lib/tasks/scheduler.rake
@viroulep 
J'ai pas du tout testé de peur de synchroniser n'importe quoi.
Je me suis basé sur ce que tu avais fait pour les autres synchronisations. Je peux te laisser vérifier et tester que ça se passe bien ?
> Sync mailing list discussion

- app/views/users/index.html.erb
Voilà ce que ça rend (tu apprécieras mes compétences en floutage d'infos persos)
> Show optins in users index

- app/mailers/notification_mailer.rb
- app/views/notification_mailer/notify_of_new_competition.html.erb
- app/views/notification_mailer/notify_of_new_competition.text.erb
Tell what to do in case people have questions
Use bcc instead of to
> Small improvements in new competition email

- app/views/bags/edit.html.erb
- app/views/bags/index.html.erb
- app/views/bags/new.html.erb
- app/views/bags/show.html.erb
- app/views/hardwares/edit.html.erb
- app/views/hardwares/index.html.erb
- app/views/hardwares/new.html.erb
- app/views/hardwares/show.html.erb
- app/views/shared/_show_owners_list.html.erb
- app/webpacker/src/hardwares.scss
Add page_wrapper
Change some links into buttons
Add links to bags in hardwares view
Display owners as table
Closes #58
> Hardwares and bags views improvements

- app/mailers/notification_mailer.rb
- app/views/notification_mailer/send_backup_to_team.html.erb
- app/views/notification_mailer/send_backup_to_team.text.erb
- lib/tasks/backup.rake
- scripts/afs_bootstrap.sh
- scripts/backup_db.sh
> Add backup script

- app/controllers/users_controller.rb
- app/models/user.rb
> Fix editing an admin by another admin

- app/views/notification_mailer/notify_of_new_competition.html.erb
- app/views/notification_mailer/notify_of_new_competition.text.erb
> Ajout d'infos dans le mail d'annonce de compétitions

- app/helpers/application_helper.rb
- app/models/user.rb
Erreur qui s'est produite sur le dépôt madrilène, je suis à peu près sûr que c'est à cause de la liste des pays qui est périmée, mais je vais vérifier avec Ivan.
Au pire ça nous rend résilient à d'autres mises à jour.
Je merge pas direct parce que je peux pas deploy là.
> Check before calling downcase

- app/views/users/edit.html.erb
- config/locales/fr.yml
> Add disclaimer in profile for mail subscriptions

- app/views/users/index.html.erb
- app/webpacker/packs/stylesheets.scss
- app/webpacker/src/variables.scss
Closes #102 
J'espère que c'est pas trop crade comme façon de faire ;)
> Add green bg to users with active subscription

- config/locales/en.yml
- config/locales/fr.yml
Updated FR (minor) and EN (added non-localized strings and updated existing string to be consistent)
> Update YAML locale files

- app/views/pages/cellule-ecoute.html.erb
- app/views/pages/contact.html.erb
- app/views/shared/_nav_contact.html.erb
- config/locales/fr.yml
Add contact menu at top of contact page
Create Counseling team page
Update FR localization accordingly
> Creation of counseling team info page

- app/views/pages/speedcubing/cdf.html.erb
- app/views/pages/speedcubing/cdf_historique.html.erb
Update French nats commission information and layout.
> Update CDF pages

- README.md
- app/controllers/subscriptions_controller.rb
- app/views/subscriptions/edit.html.erb
- app/views/subscriptions/review_import.html.erb
- config/locales/fr.yml
- db/migrate/20250221225813_update_subscriptions_schema.rb
- db/schema.rb
HelloAsso has changed the CSV quite a bit, this includes the necessary migration and changes to be able to import again subscriptions.
> Update subscriptions import

- app/views/subscriptions/subscriptions_list.html.erb
- config/locales/fr.yml
Voilà le nouveau lien Helloasso pour télécharger les adhérents (pas de lien direct, c'est un bouton qui lance un script on dirait). J'ai aussi rajouté des petites infos sur le texte fr (pas testé si l'échappement des guillemets fonctionne bien).
> Update subscriptions import link
